# Generated by Django 3.2.6 on 2024-06-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='file_name', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
